quality:
  1: 垃圾
  2: 普通
  3: 稀有
  4: 史诗
  5: 传说
  6: 奇迹
  7: 神秘
notification:
  1: 品质不好呢，残念ですね...
  2: 一般般啦...
  3: 蛮稀有的耶~
  4: 哎呀，真是少见！
  5: 恭喜！！很幸运喔~
  6: 这是神迹吗？！
  7: 闻所未闻的东西欸，这是什么...？
prob:
  1: 100.0
  2: 30.0
  3: 20.0
  4: 10.0
  5: 5.0
  6: 0.5
  7: 0.05
item:
  1:
    1001: { name: 拖把树, quality: 1, value: 0 }
    1002: { name: 破布树, quality: 1, value: 0 }
    1003: { name: 男酮树, quality: 1, value: 0 }
    1004: { name: 枯树, quality: 1, value: 0 }
    1005: { name: 假树, quality: 1, value: 0 }
    1006: { name: 蛀虫树, quality: 1, value: 0 }
  2:
    2001: { name: 倪头树, quality: 2, value: 5 }
    2002: { name: 苹果树, quality: 2, value: 5 }
    2003: { name: 杨树, quality: 2, value: 5 }
    2004: { name: 柳树, quality: 2, value: 5 }
    2005: { name: 槐树, quality: 2, value: 5 }
    2006: { name: 桦树, quality: 2, value: 5 }
  3:
    3001: { name: 金合欢树, quality: 3, value: 10 }
    3002: { name: 面包树, quality: 3, value: 10 }
    3003: { name: 黄花梨, quality: 3, value: 10 }
    3004: { name: 紫荆木, quality: 3, value: 10 }
    3005: { name: 紫檀木, quality: 3, value: 10 }
    3006: { name: 香果树, quality: 3, value: 10 }
  4:
    4001: { name: 圣诞树, quality: 4, value: 10 }
    4002: { name: 西府海棠, quality: 4, value: 30 }
    4003: { name: 彩虹桉树, quality: 4, value: 30 }
    4004: { name: 樱花树, quality: 4, value: 30 }
    4005: { name: 龙血树, quality: 4, value: 30 }
  5:
    5001: { name: 雷曼将军树, quality: 5, value: 100 }
    5002: { name: 月之女神杜鹃花树, quality: 5, value: 100 }
    5003: { name: 大唐观音银杏树, quality: 5, value: 100 }
    5004: { name: 卡罗来纳天使橡树, quality: 5, value: 100 }
  6:
    6001: { name: 生命之树, quality: 6, value: 1000 }
    6002: { name: 人参果树, quality: 6, value: 1000 }
    6003: { name: 扶桑, quality: 6, value: 1000 }
    6004: { name: 月桂树, quality: 6, value: 1000 }
  7:
    7001: { name: 建木, quality: 7, value: 99999 }
    7002: { name: 世界之树, quality: 7, value: 99999 }
    7003: { name: 猫猫神树, quality: 7, value: 99999 }
mask:
  0.1:
    1: 1.0
    2: 0.2
    3: 0.1
    4: 0.0
    5: 0.0
    6: 0.0
    7: 0.0
  0.5:
    1: 1.0
    2: 0.5
    3: 0.3
    4: 0.1
    5: 0.0
    6: 0.0
    7: 0.0
  1.0:
    1: 1.0
    2: 0.8
    3: 0.5
    4: 0.3
    5: 0.0
    6: 0.0
    7: 0.0
  5:
    1: 1.0
    2: 1.0
    3: 0.8
    4: 0.5
    5: 0.0
    6: 0.0
    7: 0.0
  10:
    1: 1.0
    2: 1.2
    3: 1.0
    4: 0.8
    5: 0.2
    6: 0.0
    7: 0.0
  20:
    1: 1.0
    2: 1.5
    3: 1.2
    4: 1.0
    5: 0.5
    6: 0.0
    7: 0.0
  30:
    1: 1.0
    2: 1.6
    3: 1.2
    4: 0.8
    5: 0.4
    6: 1.0
    7: 1.0
  40:
    1: 1.0
    2: 2.0
    3: 2.0
    4: 1.3
    5: 1.0
    6: 1.0
    7: 1.0
  100:
    1: 1.0
    2: 2.0
    3: 3.0
    4: 5.0
    5: 4.0
    6: 1.0
    7: 1.0